language: cpp

services:
- docker

before_install:
- docker build -t cycycyc/centos-build .

script:
- mkdir -p targets/centos
- docker run --rm -v ${PWD}:/mnt -w /mnt cycycyc/centos-build /bin/bash build_centos.sh
- cp ffmpeg/ffmpeg targets/centos
- mkdir -p targets/win32
- docker run --rm -v ${PWD}:/mnt -w /mnt cycycyc/centos-build /bin/bash build_mingw32.sh
- cp ffmpeg/ffmpeg.exe ffmpeg/*.dll targets/win32
- mkdir -p targets/win64
- docker run --rm -v ${PWD}:/mnt -w /mnt cycycyc/centos-build /bin/bash build_mingw64.sh
- cp ffmpeg/ffmpeg.exe ffmpeg/*.dll targets/win64
